# Generated by Django 5.2.8 on 2025-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuario', models.CharField(choices=[('A', 'Usuário A'), ('B', 'Usuário B')], max_length=1)),
                ('resposta_chatbot', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
